import { readFile, mkdir, writeFile } from "node:fs/promises";

const logos = [
  "chrome",
  "firefox",
  "safari",
  "microsoft-edge",
  "opera",
  "brave",
  "vivaldi-icon",
  "android-icon",
  "apple",
  "microsoft-windows-icon",
  "linux-tux",
  "ubuntu",
  "bing",
  "duckduckgo",
  "facebook",
  "github-icon",
  "google-icon",
  "instagram-icon",
  "linkedin-icon",
  "mailchimp-icon",
  "producthunt",
  "reddit-icon",
  "tiktok-icon",
  "twitter",
  "ycombinator",
  "youtube-icon",
];
for (const collection of ["circle-flags", "logos"]) {
  const data = JSON.parse(
    await readFile(
      new URL(import.meta.resolve(`@iconify-json/${collection}/icons.json`)),
      "utf8",
    ),
  );
  const names =
    collection === "logos"
      ? logos
      : Object.keys(data.icons).filter((name) => /^[a-z]{2}$/.test(name));
  const directory = `public/icons/${collection}`;
  await mkdir(directory, { recursive: true });
  for (const name of names) {
    const icon = data.icons[name];
    await writeFile(
      `${directory}/${name}.svg`,
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${icon.width ?? data.width ?? 16} ${icon.height ?? data.height ?? 16}">${icon.body}</svg>\n`,
    );
    if (collection === "logos" && name === "apple") {
      await writeFile(
        `${directory}/apple-dark.svg`,
        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${icon.width ?? data.width ?? 16} ${icon.height ?? data.height ?? 16}">${icon.body.replace(/<path /g, '<path fill="#E5E9ED" ')}</svg>\n`,
      );
    }
    if (collection === "logos" && name === "github-icon") {
      await writeFile(
        `${directory}/github-icon-dark.svg`,
        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${icon.width ?? data.width ?? 16} ${icon.height ?? data.height ?? 16}">${icon.body.replaceAll("#161614", "#E5E9ED")}</svg>\n`,
      );
    }
  }
  if (collection === "circle-flags") {
    await writeFile(
      "src/features/dashboard/country-flags.ts",
      `// Generated by scripts/generate-icons.mjs\nexport const countryFlags = new Set(${JSON.stringify(names.sort())});\n`,
    );
  }
}
