/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AppAppIndexRouteImport } from './routes/_app/app/index'
import { Route as AppAppAccessRouteImport } from './routes/_app/app/access'
import { Route as AppAppBillingRouteImport } from './routes/_app/app/billing'
import { Route as AppAppSiteIdIndexRouteImport } from './routes/_app/app/$siteId/index'
import { Route as AppAppSiteIdEventsRouteImport } from './routes/_app/app/$siteId/events'
import { Route as AppAppSiteIdFunnelsRouteImport } from './routes/_app/app/$siteId/funnels'
import { Route as AppAppSiteIdOverviewRouteImport } from './routes/_app/app/$siteId/overview'
import { Route as AppAppSiteIdRevenueRouteImport } from './routes/_app/app/$siteId/revenue'
import { Route as AppAppSiteIdSettingsRouteImport } from './routes/_app/app/$siteId/settings'
import { Route as AppAppSiteIdSetupRouteImport } from './routes/_app/app/$siteId/setup'
import { Route as AppAppSiteIdVisitorsRouteImport } from './routes/_app/app/$siteId/visitors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppAccessRoute = AppAppAccessRouteImport.update({
  id: '/app/access',
  path: '/app/access',
  getParentRoute: () => AppRoute,
} as any)
const AppAppBillingRoute = AppAppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdIndexRoute = AppAppSiteIdIndexRouteImport.update({
  id: '/app/$siteId/',
  path: '/app/$siteId/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdEventsRoute = AppAppSiteIdEventsRouteImport.update({
  id: '/app/$siteId/events',
  path: '/app/$siteId/events',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdFunnelsRoute = AppAppSiteIdFunnelsRouteImport.update({
  id: '/app/$siteId/funnels',
  path: '/app/$siteId/funnels',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdOverviewRoute = AppAppSiteIdOverviewRouteImport.update({
  id: '/app/$siteId/overview',
  path: '/app/$siteId/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdRevenueRoute = AppAppSiteIdRevenueRouteImport.update({
  id: '/app/$siteId/revenue',
  path: '/app/$siteId/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdSettingsRoute = AppAppSiteIdSettingsRouteImport.update({
  id: '/app/$siteId/settings',
  path: '/app/$siteId/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdSetupRoute = AppAppSiteIdSetupRouteImport.update({
  id: '/app/$siteId/setup',
  path: '/app/$siteId/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdVisitorsRoute = AppAppSiteIdVisitorsRouteImport.update({
  id: '/app/$siteId/visitors',
  path: '/app/$siteId/visitors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/access': typeof AppAppAccessRoute
  '/app/billing': typeof AppAppBillingRoute
  '/app/': typeof AppAppIndexRoute
  '/app/$siteId/events': typeof AppAppSiteIdEventsRoute
  '/app/$siteId/funnels': typeof AppAppSiteIdFunnelsRoute
  '/app/$siteId/overview': typeof AppAppSiteIdOverviewRoute
  '/app/$siteId/revenue': typeof AppAppSiteIdRevenueRoute
  '/app/$siteId/settings': typeof AppAppSiteIdSettingsRoute
  '/app/$siteId/setup': typeof AppAppSiteIdSetupRoute
  '/app/$siteId/visitors': typeof AppAppSiteIdVisitorsRoute
  '/app/$siteId/': typeof AppAppSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/access': typeof AppAppAccessRoute
  '/app/billing': typeof AppAppBillingRoute
  '/app': typeof AppAppIndexRoute
  '/app/$siteId/events': typeof AppAppSiteIdEventsRoute
  '/app/$siteId/funnels': typeof AppAppSiteIdFunnelsRoute
  '/app/$siteId/overview': typeof AppAppSiteIdOverviewRoute
  '/app/$siteId/revenue': typeof AppAppSiteIdRevenueRoute
  '/app/$siteId/settings': typeof AppAppSiteIdSettingsRoute
  '/app/$siteId/setup': typeof AppAppSiteIdSetupRoute
  '/app/$siteId/visitors': typeof AppAppSiteIdVisitorsRoute
  '/app/$siteId': typeof AppAppSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/app/access': typeof AppAppAccessRoute
  '/_app/app/billing': typeof AppAppBillingRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/$siteId/events': typeof AppAppSiteIdEventsRoute
  '/_app/app/$siteId/funnels': typeof AppAppSiteIdFunnelsRoute
  '/_app/app/$siteId/overview': typeof AppAppSiteIdOverviewRoute
  '/_app/app/$siteId/revenue': typeof AppAppSiteIdRevenueRoute
  '/_app/app/$siteId/settings': typeof AppAppSiteIdSettingsRoute
  '/_app/app/$siteId/setup': typeof AppAppSiteIdSetupRoute
  '/_app/app/$siteId/visitors': typeof AppAppSiteIdVisitorsRoute
  '/_app/app/$siteId/': typeof AppAppSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-email'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/invite/$token'
    | '/app/access'
    | '/app/billing'
    | '/app/'
    | '/app/$siteId/events'
    | '/app/$siteId/funnels'
    | '/app/$siteId/overview'
    | '/app/$siteId/revenue'
    | '/app/$siteId/settings'
    | '/app/$siteId/setup'
    | '/app/$siteId/visitors'
    | '/app/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/invite/$token'
    | '/app/access'
    | '/app/billing'
    | '/app'
    | '/app/$siteId/events'
    | '/app/$siteId/funnels'
    | '/app/$siteId/overview'
    | '/app/$siteId/revenue'
    | '/app/$siteId/settings'
    | '/app/$siteId/setup'
    | '/app/$siteId/visitors'
    | '/app/$siteId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/check-email'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/invite/$token'
    | '/_app/app/access'
    | '/_app/app/billing'
    | '/_app/app/'
    | '/_app/app/$siteId/events'
    | '/_app/app/$siteId/funnels'
    | '/_app/app/$siteId/overview'
    | '/_app/app/$siteId/revenue'
    | '/_app/app/$siteId/settings'
    | '/_app/app/$siteId/setup'
    | '/_app/app/$siteId/visitors'
    | '/_app/app/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/access': {
      id: '/_app/app/access'
      path: '/app/access'
      fullPath: '/app/access'
      preLoaderRoute: typeof AppAppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/billing': {
      id: '/_app/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppAppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/': {
      id: '/_app/app/$siteId/'
      path: '/app/$siteId'
      fullPath: '/app/$siteId/'
      preLoaderRoute: typeof AppAppSiteIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/events': {
      id: '/_app/app/$siteId/events'
      path: '/app/$siteId/events'
      fullPath: '/app/$siteId/events'
      preLoaderRoute: typeof AppAppSiteIdEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/funnels': {
      id: '/_app/app/$siteId/funnels'
      path: '/app/$siteId/funnels'
      fullPath: '/app/$siteId/funnels'
      preLoaderRoute: typeof AppAppSiteIdFunnelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/overview': {
      id: '/_app/app/$siteId/overview'
      path: '/app/$siteId/overview'
      fullPath: '/app/$siteId/overview'
      preLoaderRoute: typeof AppAppSiteIdOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/revenue': {
      id: '/_app/app/$siteId/revenue'
      path: '/app/$siteId/revenue'
      fullPath: '/app/$siteId/revenue'
      preLoaderRoute: typeof AppAppSiteIdRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/settings': {
      id: '/_app/app/$siteId/settings'
      path: '/app/$siteId/settings'
      fullPath: '/app/$siteId/settings'
      preLoaderRoute: typeof AppAppSiteIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/setup': {
      id: '/_app/app/$siteId/setup'
      path: '/app/$siteId/setup'
      fullPath: '/app/$siteId/setup'
      preLoaderRoute: typeof AppAppSiteIdSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/visitors': {
      id: '/_app/app/$siteId/visitors'
      path: '/app/$siteId/visitors'
      fullPath: '/app/$siteId/visitors'
      preLoaderRoute: typeof AppAppSiteIdVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppAccessRoute: typeof AppAppAccessRoute
  AppAppBillingRoute: typeof AppAppBillingRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppSiteIdEventsRoute: typeof AppAppSiteIdEventsRoute
  AppAppSiteIdFunnelsRoute: typeof AppAppSiteIdFunnelsRoute
  AppAppSiteIdOverviewRoute: typeof AppAppSiteIdOverviewRoute
  AppAppSiteIdRevenueRoute: typeof AppAppSiteIdRevenueRoute
  AppAppSiteIdSettingsRoute: typeof AppAppSiteIdSettingsRoute
  AppAppSiteIdSetupRoute: typeof AppAppSiteIdSetupRoute
  AppAppSiteIdVisitorsRoute: typeof AppAppSiteIdVisitorsRoute
  AppAppSiteIdIndexRoute: typeof AppAppSiteIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppAccessRoute: AppAppAccessRoute,
  AppAppBillingRoute: AppAppBillingRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppSiteIdEventsRoute: AppAppSiteIdEventsRoute,
  AppAppSiteIdFunnelsRoute: AppAppSiteIdFunnelsRoute,
  AppAppSiteIdOverviewRoute: AppAppSiteIdOverviewRoute,
  AppAppSiteIdRevenueRoute: AppAppSiteIdRevenueRoute,
  AppAppSiteIdSettingsRoute: AppAppSiteIdSettingsRoute,
  AppAppSiteIdSetupRoute: AppAppSiteIdSetupRoute,
  AppAppSiteIdVisitorsRoute: AppAppSiteIdVisitorsRoute,
  AppAppSiteIdIndexRoute: AppAppSiteIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
