/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AppAppIndexRouteImport } from './routes/_app/app/index'
import { Route as AppAppAccessRouteImport } from './routes/_app/app/access'
import { Route as AppAppBillingRouteImport } from './routes/_app/app/billing'
import { Route as AppAppSiteIdIndexRouteImport } from './routes/_app/app/$siteId/index'
import { Route as AppAppSiteIdEventsRouteImport } from './routes/_app/app/$siteId/events'
import { Route as AppAppSiteIdFunnelsRouteImport } from './routes/_app/app/$siteId/funnels'
import { Route as AppAppSiteIdOverviewRouteImport } from './routes/_app/app/$siteId/overview'
import { Route as AppAppSiteIdRevenueRouteImport } from './routes/_app/app/$siteId/revenue'
import { Route as AppAppSiteIdSettingsRouteImport } from './routes/_app/app/$siteId/settings'
import { Route as AppAppSiteIdVisitorsRouteImport } from './routes/_app/app/$siteId/visitors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppAccessRoute = AppAppAccessRouteImport.update({
  id: '/app/access',
  path: '/app/access',
  getParentRoute: () => AppRoute,
} as any)
const AppAppBillingRoute = AppAppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdIndexRoute = AppAppSiteIdIndexRouteImport.update({
  id: '/app/$siteId/',
  path: '/app/$siteId/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdEventsRoute = AppAppSiteIdEventsRouteImport.update({
  id: '/app/$siteId/events',
  path: '/app/$siteId/events',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdFunnelsRoute = AppAppSiteIdFunnelsRouteImport.update({
  id: '/app/$siteId/funnels',
  path: '/app/$siteId/funnels',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdOverviewRoute = AppAppSiteIdOverviewRouteImport.update({
  id: '/app/$siteId/overview',
  path: '/app/$siteId/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdRevenueRoute = AppAppSiteIdRevenueRouteImport.update({
  id: '/app/$siteId/revenue',
  path: '/app/$siteId/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdSettingsRoute = AppAppSiteIdSettingsRouteImport.update({
  id: '/app/$siteId/settings',
  path: '/app/$siteId/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSiteIdVisitorsRoute = AppAppSiteIdVisitorsRouteImport.update({
  id: '/app/$siteId/visitors',
  path: '/app/$siteId/visitors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/access': typeof AppAppAccessRoute
  '/app/billing': typeof AppAppBillingRoute
  '/app/': typeof AppAppIndexRoute
  '/app/$siteId/events': typeof AppAppSiteIdEventsRoute
  '/app/$siteId/funnels': typeof AppAppSiteIdFunnelsRoute
  '/app/$siteId/overview': typeof AppAppSiteIdOverviewRoute
  '/app/$siteId/revenue': typeof AppAppSiteIdRevenueRoute
  '/app/$siteId/settings': typeof AppAppSiteIdSettingsRoute
  '/app/$siteId/visitors': typeof AppAppSiteIdVisitorsRoute
  '/app/$siteId/': typeof AppAppSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/access': typeof AppAppAccessRoute
  '/app/billing': typeof AppAppBillingRoute
  '/app': typeof AppAppIndexRoute
  '/app/$siteId/events': typeof AppAppSiteIdEventsRoute
  '/app/$siteId/funnels': typeof AppAppSiteIdFunnelsRoute
  '/app/$siteId/overview': typeof AppAppSiteIdOverviewRoute
  '/app/$siteId/revenue': typeof AppAppSiteIdRevenueRoute
  '/app/$siteId/settings': typeof AppAppSiteIdSettingsRoute
  '/app/$siteId/visitors': typeof AppAppSiteIdVisitorsRoute
  '/app/$siteId': typeof AppAppSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/app/access': typeof AppAppAccessRoute
  '/_app/app/billing': typeof AppAppBillingRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/$siteId/events': typeof AppAppSiteIdEventsRoute
  '/_app/app/$siteId/funnels': typeof AppAppSiteIdFunnelsRoute
  '/_app/app/$siteId/overview': typeof AppAppSiteIdOverviewRoute
  '/_app/app/$siteId/revenue': typeof AppAppSiteIdRevenueRoute
  '/_app/app/$siteId/settings': typeof AppAppSiteIdSettingsRoute
  '/_app/app/$siteId/visitors': typeof AppAppSiteIdVisitorsRoute
  '/_app/app/$siteId/': typeof AppAppSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/invite/$token'
    | '/app/access'
    | '/app/billing'
    | '/app/'
    | '/app/$siteId/events'
    | '/app/$siteId/funnels'
    | '/app/$siteId/overview'
    | '/app/$siteId/revenue'
    | '/app/$siteId/settings'
    | '/app/$siteId/visitors'
    | '/app/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/invite/$token'
    | '/app/access'
    | '/app/billing'
    | '/app'
    | '/app/$siteId/events'
    | '/app/$siteId/funnels'
    | '/app/$siteId/overview'
    | '/app/$siteId/revenue'
    | '/app/$siteId/settings'
    | '/app/$siteId/visitors'
    | '/app/$siteId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/invite/$token'
    | '/_app/app/access'
    | '/_app/app/billing'
    | '/_app/app/'
    | '/_app/app/$siteId/events'
    | '/_app/app/$siteId/funnels'
    | '/_app/app/$siteId/overview'
    | '/_app/app/$siteId/revenue'
    | '/_app/app/$siteId/settings'
    | '/_app/app/$siteId/visitors'
    | '/_app/app/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/access': {
      id: '/_app/app/access'
      path: '/app/access'
      fullPath: '/app/access'
      preLoaderRoute: typeof AppAppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/billing': {
      id: '/_app/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppAppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/': {
      id: '/_app/app/$siteId/'
      path: '/app/$siteId'
      fullPath: '/app/$siteId/'
      preLoaderRoute: typeof AppAppSiteIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/events': {
      id: '/_app/app/$siteId/events'
      path: '/app/$siteId/events'
      fullPath: '/app/$siteId/events'
      preLoaderRoute: typeof AppAppSiteIdEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/funnels': {
      id: '/_app/app/$siteId/funnels'
      path: '/app/$siteId/funnels'
      fullPath: '/app/$siteId/funnels'
      preLoaderRoute: typeof AppAppSiteIdFunnelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/overview': {
      id: '/_app/app/$siteId/overview'
      path: '/app/$siteId/overview'
      fullPath: '/app/$siteId/overview'
      preLoaderRoute: typeof AppAppSiteIdOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/revenue': {
      id: '/_app/app/$siteId/revenue'
      path: '/app/$siteId/revenue'
      fullPath: '/app/$siteId/revenue'
      preLoaderRoute: typeof AppAppSiteIdRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/settings': {
      id: '/_app/app/$siteId/settings'
      path: '/app/$siteId/settings'
      fullPath: '/app/$siteId/settings'
      preLoaderRoute: typeof AppAppSiteIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/$siteId/visitors': {
      id: '/_app/app/$siteId/visitors'
      path: '/app/$siteId/visitors'
      fullPath: '/app/$siteId/visitors'
      preLoaderRoute: typeof AppAppSiteIdVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppAccessRoute: typeof AppAppAccessRoute
  AppAppBillingRoute: typeof AppAppBillingRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppSiteIdEventsRoute: typeof AppAppSiteIdEventsRoute
  AppAppSiteIdFunnelsRoute: typeof AppAppSiteIdFunnelsRoute
  AppAppSiteIdOverviewRoute: typeof AppAppSiteIdOverviewRoute
  AppAppSiteIdRevenueRoute: typeof AppAppSiteIdRevenueRoute
  AppAppSiteIdSettingsRoute: typeof AppAppSiteIdSettingsRoute
  AppAppSiteIdVisitorsRoute: typeof AppAppSiteIdVisitorsRoute
  AppAppSiteIdIndexRoute: typeof AppAppSiteIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppAccessRoute: AppAppAccessRoute,
  AppAppBillingRoute: AppAppBillingRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppSiteIdEventsRoute: AppAppSiteIdEventsRoute,
  AppAppSiteIdFunnelsRoute: AppAppSiteIdFunnelsRoute,
  AppAppSiteIdOverviewRoute: AppAppSiteIdOverviewRoute,
  AppAppSiteIdRevenueRoute: AppAppSiteIdRevenueRoute,
  AppAppSiteIdSettingsRoute: AppAppSiteIdSettingsRoute,
  AppAppSiteIdVisitorsRoute: AppAppSiteIdVisitorsRoute,
  AppAppSiteIdIndexRoute: AppAppSiteIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
